library(tm)
### The Beer Winners
# Run this code after uploading RecipeData.Rda
# Or if you ran Recipe Scraping-1

### Code to tag the ID to the document
myReader1 <- readTabular(mapping=list(content="ingredients", id="recipe"))

### Remove punctuation and adding spacing for preprocessing
data.clean <- data
data.clean$ingredients<-gsub('"', "", data.clean$ingredients)
data.clean$ingredients<-gsub(',', " ", data.clean$ingredients)
data.clean$ingredients<-gsub("_"," ",data.clean$ingredients)
data.clean$ingredients<-gsub("-","",data.clean$ingredients)

### Remove words that show up in ingredients list that are inefficient
data.clean$ingredients<-gsub("Kraft","",data.clean$ingredients)
data.clean$ingredients<-gsub("freshly","",data.clean$ingredients)
data.clean$ingredients<-gsub("fresh","",data.clean$ingredients)
data.clean$ingredients<-gsub("yolk","",data.clean$ingredients)
data.clean$ingredients<-gsub("ground","",data.clean$ingredients)
data.clean$ingredients<-gsub("dried","",data.clean$ingredients)
data.clean$ingredients<-gsub("extravirgin","",data.clean$ingredients)
data.clean$ingredients<-gsub("kosher","",data.clean$ingredients)
data.clean$ingredients<-gsub("unsalted","",data.clean$ingredients)
data.clean$ingredients<-gsub("allpurpose","",data.clean$ingredients)
data.clean$ingredients<-gsub("granulated","",data.clean$ingredients)
data.clean$ingredients<-gsub("chopped","",data.clean$ingredients)
data.clean$ingredients<-gsub("shredded","",data.clean$ingredients)
data.clean$ingredients<-gsub("light","",data.clean$ingredients)
data.clean$ingredients<-gsub("crushed","",data.clean$ingredients)
data.clean$ingredients<-gsub("yoghurt","yogurt",data.clean$ingredients)
data.clean$ingredients<-gsub("skinless","",data.clean$ingredients)
data.clean$ingredients<-gsub("nonfat","",data.clean$ingredients)
data.clean$ingredients<-gsub("lowfat","",data.clean$ingredients)
data.clean$ingredients<-gsub("large","",data.clean$ingredients)
data.clean$ingredients<-gsub("baby","",data.clean$ingredients)
data.clean$ingredients<-gsub("minced","",data.clean$ingredients)
data.clean$ingredients<-gsub("melted","",data.clean$ingredients)
data.clean$ingredients<-gsub("whole","",data.clean$ingredients)
data.clean$ingredients<-gsub("diced","",data.clean$ingredients)
data.clean$ingredients<-gsub("boneless","",data.clean$ingredients)
data.clean$ingredients<-gsub("frozen","",data.clean$ingredients)
data.clean$ingredients<-gsub("dark","",data.clean$ingredients)
data.clean$ingredients<-gsub("reduced","",data.clean$ingredients)
data.clean$ingredients<-gsub("canned","",data.clean$ingredients)
data.clean$ingredients<-gsub("sliced","",data.clean$ingredients)
data.clean$ingredients<-gsub("low","",data.clean$ingredients)
data.clean$ingredients<-gsub("sodium","",data.clean$ingredients)
data.clean$ingredients<-gsub("extra","",data.clean$ingredients)
data.clean$ingredients<-gsub("virgin","",data.clean$ingredients)
data.clean$ingredients<-gsub("purple onion","purpleonion",data.clean$ingredients)
data.clean$ingredients<-gsub("black pepper","blackpepper",data.clean$ingredients)
data.clean$ingredients<-gsub("grated parmesan cheese","gratedparmesancheese",data.clean$ingredients)
data.clean$ingredients<-gsub("grated parmesan","gratedparmesancheese",data.clean$ingredients)
data.clean$ingredients<-gsub("Grated Parmesan Cheese","gratedparmesancheese",data.clean$ingredients)
data.clean$ingredients<-gsub("red pepper flakes","redpepperflakes",data.clean$ingredients)
data.clean$ingredients<-gsub("red wine","redwine",data.clean$ingredients)
data.clean$ingredients<-gsub("yellow onion","yellowonion",data.clean$ingredients)
data.clean$ingredients<-gsub("club soda","clubsoda",data.clean$ingredients)
data.clean$ingredients<-gsub("simple syrup","simplesyrup",data.clean$ingredients)
data.clean$ingredients<-gsub("white rum","whiterum",data.clean$ingredients)
data.clean$ingredients<-gsub("white wine","whitewine",data.clean$ingredients)
data.clean$ingredients<-gsub("carbonated water","carbonatedwater",data.clean$ingredients)
data.clean$ingredients<-gsub("leav","",data.clean$ingredients)
data.clean$ingredients<-gsub("white sugar","whitesugar",data.clean$ingredients)
data.clean$ingredients<-gsub("brown sugar","brownsugar",data.clean$ingredients)
data.clean$ingredients<-gsub("dry yeast","dryyeast",data.clean$ingredients)
data.clean$ingredients<-gsub("unbleached flour","unbleachedflour",data.clean$ingredients)
data.clean$ingredients<-gsub("powdered sugar","powderedsugar",data.clean$ingredients)
data.clean$ingredients<-gsub("seed","",data.clean$ingredients)
data.clean$ingredients<-gsub("powder","",data.clean$ingredients)
data.clean$ingredients<-gsub("cayenne pepper","cayennepepper",data.clean$ingredients)
data.clean$ingredients<-gsub("plain flour","plainflour",data.clean$ingredients)
data.clean$ingredients<-gsub("plain yogurt","plainyogurt",data.clean$ingredients)
data.clean$ingredients<-gsub("red chile pepper","redchilepepper",data.clean$ingredients)
data.clean$ingredients<-gsub("curry leav","curryleav",data.clean$ingredients)
data.clean$ingredients<-gsub("cilantro leav","cilantroleav",data.clean$ingredients)
data.clean$ingredients<-gsub("green chili","greenchili",data.clean$ingredients)
data.clean$ingredients<-gsub("soy sauce","soysauce",data.clean$ingredients)
data.clean$ingredients<-gsub("green bell pepper","greenbellpepper",data.clean$ingredients)
data.clean$ingredients<-gsub("green onion","greenonion",data.clean$ingredients)
data.clean$ingredients<-gsub("corn starch","cornstarch",data.clean$ingredients)
data.clean$ingredients<-gsub("red bell pepper","redbellpepper",data.clean$ingredients)
data.clean$ingredients<-gsub("white rice","whiterice",data.clean$ingredients)
data.clean$ingredients<-gsub("red pepper flak","redpepperflak",data.clean$ingredients)
data.clean$ingredients<-gsub("fish sauce","fishsauce",data.clean$ingredients)
data.clean$ingredients<-gsub("curry paste","currypaste",data.clean$ingredients)
data.clean$ingredients<-gsub("miso paste","misopaste",data.clean$ingredients)
data.clean$ingredients<-gsub("coconut milk","coconutmilk",data.clean$ingredients)
data.clean$ingredients<-gsub("heavy cream","heavycream",data.clean$ingredients)
data.clean$ingredients<-gsub("egg whit","eggwhite",data.clean$ingredients)
data.clean$ingredients<-gsub("chocolate chip","chocolatechip",data.clean$ingredients)
data.clean$ingredients<-gsub("baking soda","bakingsoda",data.clean$ingredients)
data.clean$ingredients<-gsub("baking ","bakingpowder",data.clean$ingredients)
data.clean$ingredients<-gsub("granny smith apple","grannysmithapple",data.clean$ingredients)
data.clean$ingredients<-gsub("leaves","",data.clean$ingredients)
data.clean$ingredients<-gsub("red wine vinegar","redwinevinegar",data.clean$ingredients)
data.clean$ingredients<-gsub("lemon juice","lemonjuice",data.clean$ingredients)
data.clean$ingredients<-gsub("lime juice","limejuice",data.clean$ingredients)
data.clean$ingredients<-gsub("greek yogurt","greekyogurt",data.clean$ingredients)
data.clean$ingredients<-gsub("lemon zest","lemonzest",data.clean$ingredients)
data.clean$ingredients<-gsub("white flour","whiteflour",data.clean$ingredients)
data.clean$ingredients<-gsub("chicken breast","chicken",data.clean$ingredients)
data.clean$ingredients<-gsub("worcestershire sauce","worcestershiresauce",data.clean$ingredients)
data.clean$ingredients<-gsub("saffron thread","saffronthread",data.clean$ingredients)
data.clean$ingredients<-gsub("smoked paprika","smokedpaprika",data.clean$ingredients)
data.clean$ingredients<-gsub("chicken broth","chickenbroth",data.clean$ingredients)
data.clean$ingredients<-gsub("vegetable broth","vegetablebroth",data.clean$ingredients)
data.clean$ingredients<-gsub("bay leav","bayleav",data.clean$ingredients)


### Corpus clean up tasks
corpus <- Corpus(DataframeSource(data.clean),readerControl=list(reader=myReader1))
corpus <- tm_map(corpus, removePunctuation)

### Create dtm to review
dtm <- DocumentTermMatrix(corpus)
dtm2 <- as.matrix(dtm)
frequency <- colSums(dtm2)
frequency <- sort(frequency, decreasing=TRUE)
head(frequency)

### Create dataframe for ingredients
freq.df <- as.data.frame(frequency)
freq.df$ingredient <- row.names(freq.df)
freq.df <- as.data.frame(freq.df, row.names = 1:length(freq.df$frequency))
View(freq.df)
