datatdm<-data
datatdm$ingredients<-gsub('"', "", datatdm$ingredients)
datatdm$ingredients<-gsub(',', " ", datatdm$ingredients)

ingredient_text <- paste(datatdm$ingredients, collapse=" ")
ingredient_source <- VectorSource(ingredient_text)
corpus <- Corpus(ingredient_source)
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, stripWhitespace)
dtm <- DocumentTermMatrix(corpus)
dtm2 <- as.matrix(dtm)
frequency <- colSums(dtm2)
frequency <- sort(frequency, decreasing=TRUE)
View(frequency)

datatdm$ingredients<-gsub("-","",datatdm$ingredients)
datatdm$ingredients<-gsub("_","",datatdm$ingredients)
datatdm$ingredients<-gsub("kraft","",datatdm$ingredients)
datatdm$ingredients<-gsub("freshly","",datatdm$ingredients)
datatdm$ingredients<-gsub("fresh","",datatdm$ingredients)
datatdm$ingredients<-gsub("yolk","",datatdm$ingredients)
datatdm$ingredients<-gsub("ground","",datatdm$ingredients)
datatdm$ingredients<-gsub("dried","",datatdm$ingredients)
datatdm$ingredients<-gsub("extravirgin","",datatdm$ingredients)
datatdm$ingredients<-gsub("kosher","",datatdm$ingredients)
datatdm$ingredients<-gsub("unsalted","",datatdm$ingredients)
datatdm$ingredients<-gsub("allpurpose","",datatdm$ingredients)
datatdm$ingredients<-gsub("granulated","",datatdm$ingredients)
datatdm$ingredients<-gsub("bonelessskinless","",datatdm$ingredients)
datatdm$ingredients<-gsub("chopped","",datatdm$ingredients)
datatdm$ingredients<-gsub("blackpepper","pepper",datatdm$ingredients)
datatdm$ingredients<-gsub("shredded","",datatdm$ingredients)
datatdm$ingredients<-gsub("light","",datatdm$ingredients)
datatdm$ingredients<-gsub("crushed","",datatdm$ingredients)
datatdm$ingredients<-gsub("yoghurt","yogurt",datatdm$ingredients)
datatdm$ingredients<-gsub("skinless","",datatdm$ingredients)
datatdm$ingredients<-gsub("nonfat","",datatdm$ingredients)
datatdm$ingredients<-gsub("lowfat","",datatdm$ingredients)
datatdm$ingredients<-gsub("large","",datatdm$ingredients)
datatdm$ingredients<-gsub("baby","",datatdm$ingredients)
datatdm$ingredients<-gsub("minced","",datatdm$ingredients)
datatdm$ingredients<-gsub("melted","",datatdm$ingredients)
datatdm$ingredients<-gsub("whole","",datatdm$ingredients)
datatdm$ingredients<-gsub("diced","",datatdm$ingredients)
datatdm$ingredients<-gsub("boneless","",datatdm$ingredients)
datatdm$ingredients<-gsub("frozen","",datatdm$ingredients)
datatdm$ingredients<-gsub("dark","",datatdm$ingredients)
datatdm$ingredients<-gsub("reducedsodium","",datatdm$ingredients)
datatdm$ingredients<-gsub("canned","",datatdm$ingredients)
datatdm$ingredients<-gsub("sliced","",datatdm$ingredients)
datatdm$ingredients<-gsub("lowsodium","",datatdm$ingredients)

ingredient_text <- paste(datatdm$ingredients, collapse=" ")
ingredient_source <- VectorSource(ingredient_text)
corpus <- Corpus(ingredient_source)
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, stripWhitespace)
dtm <- DocumentTermMatrix(corpus)
dtm2 <- as.matrix(dtm)
frequency <- colSums(dtm2)
frequency <- sort(frequency, decreasing=TRUE)
View(frequency)